version: '3.3'

services:

  app:
    container_name: syspass-app
    image: syspass/syspass:3.2.11 
    restart: unless-stopped
    ports:
      - "8200:80"
      - "8443:443"
    depends_on:
      - db
    volumes:
      - ./syspass-config:/var/www/html/sysPass/app/config
      - ./syspass-backup:/var/www/html/sysPass/app/backup
#    environment:
#      - USE_SSL=yes
  db:
    container_name: syspass-db
    restart: unless-stopped
    image: mariadb:10.9
    environment:
      - MYSQL_USER=User
      - MYSQL_PASSWORD=p4ssw0rd     
      - MYSQL_DATABASE=syspass
      - MYSQL_ROOT_PASSWORD=p4ssw0rd  
    expose:
      - "3306"
    volumes:
      - ./syspass-db:/var/lib/mysql

